### PR TITLE
move example playbook to examples/ directory

### PR DESCRIPTION
**Pull request by richm**

### CODE REVIEW

**Comment by spetrosi** [comment]
Shouldn't the example naming follow the `example-$FILE-$ROLENAME` convention?

**Comment by pcahyna** [comment]
> Shouldn't the example naming follow the `example-$FILE-$ROLENAME` convention?

The example- part is conveyed by being in the `examples/` directory and `$ROLENAME` is unnecessary, everything inside the selinux repo belongs by definition to the selinux roie.
If the example is going to be installed together with other playbooks from some other roles, one can enforce any convention that is needed in the install script.

**Comment by richm** [comment]
so - ok to merge?

**Review by spetrosi — APPROVED** [review]
LGTM, thanks @pcahyna for the clarification

**Pull request merged**
