### PR TITLE
Move defaults to defaults/main.yml

### PR DESCRIPTION
**Pull request by major**
Signed-off-by: Major Hayden <major@redhat.com>

### CODE REVIEW

**Comment by pcahyna** [comment]
[citest commit:41a866de8bbd5be54575de5a2f30e013333003ac]

**Comment by wrabcak** [comment]
@pcahyna 
Where is CI? PR looks good but I would like to see tests passing. :) 

Thanks,
Lukas.

**Comment by pcahyna** [comment]
I don't know, there seems to be some problem with the CI. @tyll , do you know anything?

**Comment by tyll** [comment]
@pcahyna according to the GitHub API you are only considered to be a CONTRIBUTOR and not a MEMBER, therefore the CI ignores your comment. @wrabcak is considered to be a MEMBER.

**Comment by tyll** [comment]
[citest commit:41a866de8bbd5be54575de5a2f30e013333003ac]

It seems that I am also a MEMBER, let's check...

**Comment by pcahyna** [comment]
By the way, our CI did not run for https://github.com/linux-system-roles/network/pull/86 either.

**Comment by pcahyna** [comment]
@wrabcak here are your Ci results, can you merge the PR?

**Comment by wrabcak** [comment]
LGTM. 

Thanks

**Comment by pcahyna** [comment]
@yontalcar maybe use this API https://developer.github.com/v3/repos/collaborators/#review-a-users-permission-level to find out whether the user has push permissions? (Instead of checking `comment["author_association"] == "MEMBER"` https://github.com/linux-system-roles/test-harness/blob/5801b7fae06cb96818fc9308f340aa01d93b4be4/test/run-tests#L325 )

**Comment by tyll** [comment]
@pcahyna I took another look. It seems that your membership in the system roles organization is not public:
https://github.com/orgs/linux-system-roles/people

Therefore you appear as a contributor instead of a member in some cases. For example when looking at the comments in this PR with an unauthenticated browser (for example using the private mode), you are mentioned to be a contributor. But when I look after authentication, it shows you as a member. I recall that I read about the public membership to be required for external services as well.

**Comment by yontalcar** [comment]
@tyll: Looks like adding `read:org` scope to token used for `test-harness` should be sufficient to fix this.

**Comment by pcahyna** [comment]
@yontalcar great! Can you please create another (fake) PR which illustrates the problem and then we can try changing the token?
(Actually the PR should be created by somebody who is not the member of the organization probably to reproduce what happened here)

**Comment by pcahyna** [comment]
@tyll 
> I took another look. It seems that your membership in the system roles organization is not public

It's not just me. It seems that almost all members' membership is private. Anyway, thanks for discovering this.

**Pull request merged**
