### PR TITLE
ansible-lint 6.x fixes

### PR DESCRIPTION
**Pull request by richm**
No spaces inside braces and brackets
All tasks are named
All documents begin with `---`
Use `true`/`false` instead of `yes`/`no`
Other cleanup

### CODE REVIEW

**Comment by richm** [comment]
[citest]

**Comment by richm** [comment]
[citest]

**Review by bachradsusi — APPROVED** [review]

**Comment by richm** [comment]
[citest]

**Comment by richm** [comment]
[citest bad]

**Pull request merged**
