### PR TITLE
Add seuser and selevel support for selinux_fcontexts

### PR DESCRIPTION
**Pull request by benblasco**
Code and documentation changes to support the RFE #106

### CODE REVIEW

**Comment by richm** [comment]
[citest commit:d800b0b2a297317754d7b2158875cab6f6d89c7a]

**Comment by richm** [comment]
lgtm - @bachradsusi ?

**Comment by bachradsusi** [comment]
I'd just squash these 3 commits into 1 but it looks good to me.

**Comment by richm** [comment]
> > I'd just squash these 3 commits into 1 but it looks good to me.
> 
> I don't know how to do this but happy for them to be squashed together.

That can be done when the PR is merged - one of the options for merging in github is "Squash and merge" - so no need to do it now.

**Comment by richm** [comment]
Is this PR sufficient, or does the role now need to use `restorecon -F` - https://github.com/linux-system-roles/selinux/issues/106#issuecomment-1119482885 ?

**Comment by richm** [comment]
> Is this PR sufficient, or does the role now need to use `restorecon -F` - [#106 (comment)](https://github.com/linux-system-roles/selinux/issues/106#issuecomment-1119482885) ?

@bachradsusi ^^^ ?

**Comment by bachradsusi** [comment]
Sorry for the late response.

In order to make this feature complete, I'd say that `restorecon -F` would be necessary.

**Comment by richm** [comment]
@benblasco please amend your PR to add `-F` to the `restorecon` commands in tasks/main.yml

**Comment by benblasco** [comment]
Hi @richm I have made the update, but I see it captured the merge performed to update my code.  The only changes i have made this time are to the calls to `restorecon` in tasks/main.yml.

Hope this is ok.

**Comment by richm** [comment]
[citest]

**Comment by ukulekek** [comment]
[citest]

**Comment by ukulekek** [comment]
[citest]

**Comment by bachradsusi** [comment]
The changes looks good to me. As for the squashing commits, there's 7.6 Git Tools - Rewriting History chapter in the git book  - https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History

**Comment by richm** [comment]
and now the 2.13 tests are failing because the CI system doesn't yet know how to install the requirements from meta/collection-requirements.yml (which we'll be working on soon)

**Pull request merged**
