### PR TITLE
RHELPLAN-68117  Collections - Selinux - fixing ansible-test errors

### PR DESCRIPTION
**Pull request by nhosoi**
Command line:
`tox -e collection,ansible-test`

Changes:
- Removing obsolete tests/setup_module_utils.sh

- library/selogin.py
    - ERROR! module fedora.linux_system_roles.selogin missing documentation
      (or could not parse documentation): while scanning a simple key.
      Description value in serange should not be a list, but a string.
    - ERROR: plugins/modules/selogin.py:0:0: missing: from __future__ import
      (absolute_import, division, print_function).
      A boilerplate is added.
    - [WARNING]: found a duplicate dict key (author). Using last defined value only.
      Merge the two authors into one list.

- ERROR: plugins/modules/selogin.py:0:0: missing: __metaclass__ = type

- ERROR: plugins/modules/selinux_modules_facts.py:1:1: expected module
    shebang "b'#!/usr/bin/python'" but found: b'#!/usr/bin/python3'

- ERROR: plugins/modules/selinux_modules_facts.py:0:0: invalid-documentation:
    DOCUMENTATION.author: Invalid author for dictionary value @ data['author'].
    Got ['Petr Lautrbach <plautrba@redhat.com>']
    
- ERROR: plugins/modules/selogin.py:0:0: invalid-documentation:
    DOCUMENTATION.author: Invalid author for dictionary value @ data['author'].
    Got ['Dan Keder', 'Petr Lautrbach']
    
    Fix: Matching the regex: author_line in ansible_test validate-modules schema.py
    '^\w.*(\(@([\w-]+)\)|!UNKNOWN)(?![\w.])|^Ansible Core Team$|^Michael DeHaan$|^OpenStack Ansible SIG$'

- ERROR: plugins/modules/selinux_modules_facts.py:0:0: missing-examples:
    No EXAMPLES provided
    
    Fix: put empty EXAMPLES for placeholder.

- ERROR: plugins/modules/selogin.py:203:11: duplicate-except:
      Catching previously caught exception type OSError
- ERROR: plugins/modules/selogin.py:253:11: duplicate-except:
      Catching previously caught exception type OSError

- ERROR: plugins/modules/selogin.py:87:12: error: EXAMPLES: syntax error:
    found character '%' that cannot start any token (syntax)
- ERROR: plugins/modules/selogin.py:87:12: unparsable-with-libyaml:
    while scanning for the next token - found character that cannot start any token

- Adding .sanity-ansible-ignore-2.{9.10}.txt

- Use tox-lsr 2.3.0 and enable ansible-test
    - Upgrade to tox-lsr 2.3.0 which fixes several issues with running
      ansible-test sanity from tox.
    - Add ansible-test to the python 3.6 test list

### CODE REVIEW

**Comment by richm** [comment]
> ERROR: Found 9 no-get-exception issue(s) which need to be resolved

These look pretty easy and not invasive: https://docs.ansible.com/ansible/2.10/dev_guide/testing/sanity/no-get-exception.html

> ERROR: Found 10 validate-modules issue(s) which need to be resolved:
> ERROR: Found 2 yamllint issue(s) which need to be resolved:

These are module docs issues e.g. bad yaml formatting in embedded examples, or improperly documented parameters.

**Comment by nhosoi** [comment]
> > ERROR: Found 9 no-get-exception issue(s) which need to be resolved
> 
> These look pretty easy and not invasive: https://docs.ansible.com/ansible/2.10/dev_guide/testing/sanity/no-get-exception.html
> 
> > ERROR: Found 10 validate-modules issue(s) which need to be resolved:
> > ERROR: Found 2 yamllint issue(s) which need to be resolved:
> 
> These are module docs issues e.g. bad yaml formatting in embedded examples, or improperly documented parameters.
> 
> @nhosoi could you take a look at these?

Sure. Here's the errors:
- ERROR: plugins/modules/selogin.py:87:12: error: EXAMPLES: syntax error: found character '%' that cannot start any token (syntax)
- ERROR: plugins/modules/selogin.py:87:12: unparsable-with-libyaml: while scanning for the next token - found character that cannot start any token

I did not touch it since I was not sure if we can just remove `%` from the login account or not...
```
 85 # Assign all users in the engineering group to the staff_u user
 86 - selogin:
 87     login: %engineering
```

**Comment by richm** [comment]
> I did not touch it since I was not sure if we can just remove `%` from the login account or not...

You can't - man semanage-login:
```
 Prefix the group name with a '%' sign to
       indicate a group name.
```

> 
> ```
>  85 # Assign all users in the engineering group to the staff_u user
>  86 - selogin:
>  87     login: %engineering
> ```

I think you can quote the string:
```yaml
- selogin:
    login: "%engineering"
```

Works for me

**Comment by nhosoi** [comment]
@richm, could you please review this pr?

**Review by richm — APPROVED** [review]
lgtm

**Pull request merged**
