### PR TITLE
Run 'Reload SELinux policy' as a handler

### PR DESCRIPTION
**Pull request by yontalcar**
This fixes idempotency check.

Addresses: https://bugzilla.redhat.com/show_bug.cgi?id=1757857

### CODE REVIEW

**Comment by jharuda** [comment]
[citool]

**Comment by richm** [comment]
@yontalcar I think this was already done in another PR - please confirm

**Comment by jharuda** [comment]
[citest bad]

**Comment by richm** [comment]
closing - fixed in commit dd9f8f1f4f9faa18b5b1206af9e524019c05d6a1

**Pull request closed without merging**
