### PR TITLE
test: skip tests_modifications_with_selinux_disabled on EL6

### PR DESCRIPTION
**Pull request by richm**
Test is not supported on EL6

Signed-off-by: Rich Megginson <rmeggins@redhat.com>

### CODE REVIEW

**Comment by richm** [comment]
[citest]

**Comment by richm** [comment]
[citest]

**Comment by ukulekek** [comment]
[citest]

**Comment by ukulekek** [comment]
[citest]

**Comment by ukulekek** [comment]
[citest]

**Comment by ukulekek** [comment]
[citest]

**Pull request merged**
